Users docs with md title fix
xrplevm/docs.xrplevm.org pull request #1
Opened 2024-12-24 09:07 UTC by vriveraPeersyst

Had to fix title structure for:
- What is the XRPL
- What is the XRPL EVM
- What is the XRPL EVM Bridge

2025-01-08 12:31 UTC, vriveraPeersyst reviewed
Fix and improve users docs.

Add Developers docs:
- # Develop a Smart Contract
- # Deploy the Smart Contract
- # Verify a Smart Contract on the XRPL EVM
- # Interact with the Smart Contract

Missing: Next steps, create your first xrplevm user SignIn with MetaMask frontend.

2025-01-09 12:32 UTC, AdriaCarrera requested changes

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/introduction/what-is-the-xrpl-evm.md
> +---
Delete from here to bottom

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/introduction/what-is-the-xrpl-evm-bridge.md
> +---
Delete from here to bottom

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/index.md
> +
Add a welcome message like "Welcome to the XRPL EVM documentation here you can find..."

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/getting-started/introduction.md
> +# Introduction
This page is too generic and repetitive. It says same things as introduction section. Instead, add an introduction for the users that want to access to XRPL EVM. Write something like, to access all the fuctionallities of the XRPL EVM you will need an account and XRP. To get that you will need a wallet and use the bridge, in this section you will learn how to do it.

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/getting-started/install-metamask.md
> +## Attention
Remove this section and all the references that say that this project is in development

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/getting-started/install-metamask.md
> +---
Remove from here to bottom

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/getting-started/connect-to-the-xrpl-evm.md
> +## Attention
Remove this section

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/getting-started/connect-to-the-xrpl-evm.md
> +---
Remove from here to bottom

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/using-the-bridge.md
> +The XRPL EVM bridge plays a critical role in facilitating asset and data transfers between the XRP Ledger (XRPL) and the XRPL Ethereum Virtual Machine (EVM) Sidechain. Initially designed to use the *
Delete all mentions to XLS38d, it doesn't apply

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/using-the-bridge.md
> +## XLS38d Bridge
Delete this section

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/using-the-bridge.md
> +### Attention
Delete this section

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/using-the-bridge.md
Rework this page as if the Axelar bridge was the only available. Remove any mention to XLS38d. Remove mentions saying that the project is in development

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/users/faucet.md
> +### Important Details
Remove from here to bottom almost

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/developers/developing-smart-contracts/develop-a-smart-contract.md
> +4. **AI Tools (2025-Ready):**
Remove this item

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/developers/developing-smart-contracts/develop-a-smart-contract.md
> +## The Role of AI in Smart Contract Development
Remove this section

2025-01-09 12:32 UTC, AdriaCarrera commented on pages/developers/developing-smart-contracts/develop-a-smart-contract.md
> +1. **Write Your First Contract:** Start small with basic contracts like token creation or a simple voting system.
Add the links to each page in each point

2025-01-09 15:48 UTC, AdriaCarrera requested changes

2025-01-09 15:48 UTC, AdriaCarrera commented on pages/users/introduction/what-is-the-xrpl-evm-bridge.md
> +The **XRPL EVM Bridge** serves as a critical component enabling interoperability between the XRP Ledger (XRPL) and the XRPL Ethereum Virtual Machine (EVM) Sidechain. It allows users to transfer asset
Remove the XLS38d part

2025-01-09 15:48 UTC, AdriaCarrera commented on pages/users/introduction/what-is-the-xrpl-evm-bridge.md
> +The Axelar-powered bridge replaces the initial XLS38d bridge. Here's an overview of its operation:
Remove XLS38d mention

2025-01-09 15:48 UTC, AdriaCarrera commented on pages/users/getting-started/introduction.md
> +---
Remove this table of contents, instead add a read more explanation with the future steps with a link to install-metamask guide

2025-01-09 15:48 UTC, AdriaCarrera commented on pages/users/getting-started/connect-to-the-xrpl-evm.md
> +## Attention
Still needs to be reomved

2025-01-09 15:48 UTC, AdriaCarrera commented on pages/users/getting-started/connect-to-the-xrpl-evm.md
> +## Notes for Testing and Development
Remove this notes for testing

2025-01-09 15:48 UTC, merged